### PR TITLE
Fix roberta conversion bugs

### LINKED ISSUE #963: 🐛 [Bug] Failure to compile RoBERTa model with Torch-TRT
##  Bug Description

When trying to convert RoBERTa torchscript model to torch-TRT, it may trigger bugs in RoBERTa preprocessing steps.
As indicated by error messages, there's some error in `aten::ne` and `aten::cumsum`: when creating elementwise layers, the first operand is of type int32, but the second operand is of type float32.

```bash
WARNING: [Torch-TensorRT] - For input input_ids, found user specified input dtype as Int32, however when inspecting the graph, the input type expected was inferred to be Float
The compiler is going to use the user setting Int32
This conflict may cause an error at runtime due to partial compilation being enabled and therefore
compatibility with PyTorch's data type convention is required.
If you do indeed see errors at runtime either:
- Remove the dtype spec for input_ids
- Disable partial compilation by setting require_full_compilation to True
WARNING: [Torch-TensorRT] - For input attention_mask.1, found user specified input dtype as Int32, however when inspecting the graph, the input type expected was inferred to be Double
The compiler is going to use the user setting Int32
This conflict may cause an error at runtime due to partial compilation being enabled and therefore
compatibility with PyTorch's data type convention is required.
If you do indeed see errors at runtime either:
- Remove the dtype spec for attention_mask.1
- Disable partial compilation by setting require_full_compilation to True
WARNING: [Torch-TensorRT TorchScript Conversion Context] - Tensor DataType is determined at build time for tensors not marked as input or output.
WARNING: [Torch-TensorRT] - There may be undefined behavior using dynamic shape and aten::size
WARNING: [Torch-TensorRT] - There may be undefined behavior using dynamic shape and aten::size
WARNING: [Torch-TensorRT] - Truncating weight (constant in the graph) from Int64 to Int32
WARNING: [Torch-TensorRT] - Truncating weight (constant in the graph) from Float64 to Float32
WARNING: [Torch-TensorRT TorchScript Conversion Context] - IElementWiseLayer with inputs input_0 and (Unnamed Layer* 18) [Shuffle]_output: first input has type Int32 but second input has type Float.
ERROR: [Torch-TensorRT TorchScript Conversion Context] - 4: [layers.cpp::validate::2385] Error Code 4: Internal Error (%5885 : Tensor = aten::ne(%input_ids, %26), scope: __module.embeddings # /opt/conda/lib/python3.7/site-packages/transformers/models/roberta/modeling_roberta.py:1567:0is_equal: operation EQUAL has incompatible input types Int32 and Float)
ERROR: [Torch-TensorRT TorchScript Conversion Context] - 4: [layers.cpp::validate::2385] Error Code 4: Internal Error (%5885 : Tensor = aten::ne(%input_ids, %26), scope: __module.embeddings # /opt/conda/lib/python3.7/site-packages/transformers/models/roberta/modeling_roberta.py:1567:0is_equal: operation EQUAL has incompatible input types Int32 and Float)
ERROR: [Torch-TensorRT TorchScript Conversion Context] - 4: [layers.cpp::validate::2385] Error Code 4: Internal Error (%5885 : Tensor = aten::ne(%input_ids, %26), scope: __module.embeddings # /opt/conda/lib/python3.7/site-packages/transformers/models/roberta/modeling_roberta.py:1567:0is_equal: operation EQUAL has incompatible input types Int32 and Float)
ERROR: [Torch-TensorRT TorchScript Conversion Context] - 4: [layers.cpp::validate::2385] Error Code 4: Internal Error (%5885 : Tensor = aten::ne(%input_ids, %26), scope: __module.embeddings # /opt/conda/lib/python3.7/site-packages/transformers/models/roberta/modeling_roberta.py:1567:0is_equal: operation EQUAL has incompatible input types Int32 and Float)
WARNING: [Torch-TensorRT TorchScript Conversion Context] - IElementWiseLayer with inputs (Unnamed Layer* 21) [Identity]_output and (Unnamed Layer* 19) [ElementWise]_output: first input has type Float but second input has type Int32.
ERROR: [Torch-TensorRT TorchScript Conversion Context] - 2: [elementWiseNode.cpp::computeOutputExtents::14] Error Code 2: Internal Error (Assertion x.nbDims == y.nbDims failed. )
ERROR: [Torch-TensorRT TorchScript Conversion Context] - 2: [elementWiseNode.cpp::computeOutputExtents::14] Error Code 2: Internal Error (Assertion x.nbDims == y.nbDims failed. )
WARNING: [Torch-TensorRT TorchScript Conversion Context] - Tensor DataType is determined at build time for tensors not marked as input or output.
ERROR: [Torch-TensorRT TorchScript Conversion Context] - 2: [elementWiseNode.cpp::computeOutputExtents::14] Error Code 2: Internal Error (Assertion x.nbDims == y.nbDims failed. )
ERROR: [Torch-TensorRT TorchScript Conversion Context] - 2: [elementWiseNode.cpp::computeOutputExtents::14] Error Code 2: Internal Error (Assertion x.nbDims == y.nbDims failed. )
ERROR: [Torch-TensorRT TorchScript Conversion Context] - 2: [elementWiseNode.cpp::computeOutputExtents::14] Error Code 2: Internal Error (Assertion x.nbDims == y.nbDims failed. )
Traceback (most recent call last):
  File "bert.py", line 64, in <module>
    trt_ts_module = torch_tensorrt.compile(torch_script_module, **compile_settings)
  File "/opt/conda/lib/python3.7/site-packages/torch_tensorrt/_compile.py", line 115, in compile
    return torch_tensorrt.ts.compile(ts_mod, inputs=inputs, enabled_precisions=enabled_precisions, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch_tensorrt/ts/_compiler.py", line 113, in compile
    compiled_cpp_mod = _C.compile_graph(module._c, _parse_compile_spec(spec))
RuntimeError: [Error thrown at core/conversion/converters/impl/cumsum.cpp:27] Expected (dim >= 0 && dim < input_dims.nbDims) || (dim < 0 && (input_dims.nbDims + dim >= 0)) to be true but got false
Dimension out of range (expected to be in range of [1, -2], but got 1)
```

## To Reproduce

```cpp
from transformers import RobertaTokenizer, RobertaModel, RobertaConfig
import torch
import time
import numpy as np
import torch_tensorrt

enc = RobertaTokenizer.from_pretrained("roberta-base")

# Tokenizing input text
text = "[CLS] Who was Jim Henson ? [SEP] Jim Henson was a puppeteer [SEP]"
tokenized_text = enc.tokenize(text)

# Masking one of the input tokens
masked_index = 8
tokenized_text[masked_index] = '[MASK]'
indexed_tokens = enc.convert_tokens_to_ids(tokenized_text)

# Creating a dummy input
tokens_tensor = torch.tensor([indexed_tokens]).to(torch.int32).cuda()
segments_tensors = torch.ones((1, 26)).int().cuda()

dummy_input = [tokens_tensor, segments_tensors]
dummy_input_shapes = [list(v.size()) for v in dummy_input]

# Initializing the model with the torchscript flag
# If you are instantiating the model with `from_pretrained` you can also easily set the TorchScript flag
model = RobertaModel.from_pretrained("roberta-base", torchscript=True)
# The model needs to be in evaluation mode
model = model.eval().cuda()

torch_script_module = torch.jit.trace(model, (tokens_tensor, segments_tensors))

print("VERSION:", torch_tensorrt.__version__)
print("TYPE:", type(model))

print("TRY:RAW")
result = model(tokens_tensor, segments_tensors)

print("TRY:FP32")
t1 = time.time()
for i in range(10):
    result = torch_script_module(tokens_tensor, segments_tensors)
t2 = time.time()
print("Cost: ", round(t2-t1, 4))

print("COMPILE:FP32")
compile_settings = {
        "inputs": [torch_tensorrt.Input(
                shape=[1, 26],
                dtype=torch.int32,
            ),
            torch_tensorrt.Input(
                shape=[1, 26],
                dtype=torch.int32,
            )
            ],
    "require_full_compilation": False,
    "enabled_precisions": {torch.float},  # Run with FP21
    "truncate_long_and_double": True,
}

trt_ts_module = torch_tensorrt.compile(torch_script_module, **compile_settings)

print("RUN:FP32")
t1 = time.time()
for i in range(1000):
    result_trt = trt_ts_module(tokens_tensor, segments_tensors)
t2 = time.time()
print("Cost: ", round(t2-t1, 4))

diff = abs(result[0] - result_trt[0]).mean()
print('diff: {}'.format(diff))
```

## Expected behavior

The code above should run with no error and returns eligible numerical difference after conversion.

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

- Torch-TensorRT Version (e.g. 1.0.0): 1.1.0a0+7163f23a
 - PyTorch Version (e.g. 1.0): 1.10.0
 - CPU Architecture: x86_64
 - OS (e.g., Linux): Ubuntu
 - Python version: 3.7.11
 - CUDA version: 11.3
 - GPU models and configuration: A100 
 - TensorRT version: 8.2.2.1
 - Transformer versin: 4.17.0

### PR DESCRIPTION
**Pull request by Njuapp**
# Description

Fix bugs encountered when converting a RoBERTa model. 

Fixes #963 

Specifically, it fixes three things:
- For `aten::ne.Scalar(Tensor self, Scalar other) -> (Tensor)`,  the datatype of Scalar is by default initialized to be of type float. This should be int32 in this case.
- For `aten::cumsum(Tensor self, int dim, *, int? dtype=None) -> (Tensor)`, the zeroValue which stores runningSum, is by default initialized to be of type float. This should be int32 in this case. 
- For `aten::to.dtype(Tensor self, int dtype, bool non_blocking=False, bool copy=False, int? memory_format=None) -> (Tensor)`, it could be casting tensor to `long` datatype, but this cannot be processed in our code. We simply add an entry in `get_at_trt_type_map`, where `at::kLong` would be mapped to `nvinfer1::DataType::kINT32` since tensorRT could not support `long`.

## Type of change

Please delete options that are not relevant and/or add your own.

- Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project (You can use the linters)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas and hacks
- [x] I have made corresponding changes to the documentation
- [x] I have added tests to verify my fix or my feature
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: core/conversion/converters/impl/element_wise.cpp [hunk 1]
```diff
@@ -484,8 +484,12 @@ auto element_wise_registrations TORCHTRT_UNUSED =
         .pattern({"aten::ne.Scalar(Tensor self, Scalar other) -> (Tensor)",
                   [](ConversionCtx* ctx, const torch::jit::Node* n, args& args) -> bool {
                     auto self = args[0].ITensorOrFreeze(ctx);
-                    auto scalar = args[1].unwrapToScalar().to<float>();
-                    auto scalar_tensor = tensor_to_const(ctx, torch::tensor({scalar}));
+                    auto scalar = args[1].unwrapToScalar();
+                    nvinfer1::ITensor* scalar_tensor;
+                    if (scalar.isFloatingPoint())
```
Comment (narendasan) [inline core/conversion/converters/impl/element_wise.cpp:489]: Just a code style thing, would prefer if you have the brackets here

Comment (Njuapp) [reply core/conversion/converters/impl/element_wise.cpp:489]: Ok Naren, I will add brackets here.

**Comment by narendasan** [comment]
@Njuapp Can you sign your commits?

File: core/util/trt_util.cpp [hunk 2]
```diff
@@ -238,6 +238,7 @@ const std::unordered_map<at::ScalarType, nvinfer1::DataType>& get_at_trt_type_ma
       {at::kFloat, nvinfer1::DataType::kFLOAT},
       {at::kHalf, nvinfer1::DataType::kHALF},
       {at::kInt, nvinfer1::DataType::kINT32},
+      {at::kLong, nvinfer1::DataType::kINT32},
```
Comment (narendasan) [inline core/util/trt_util.cpp:241]: I dont want to just associate all instances of long with kINT32. If there are cases of kLong we should explicity handle these cases and explain what we want to do

**Review by narendasan — CHANGES_REQUESTED** [review]

File: core/util/trt_util.cpp (hunk 2 above)
Comment (narendasan) [reply core/util/trt_util.cpp:241]: So in this case in the evaluator, we can add a code path for Long in the to evaluator (when truncate is enabled) and print a warning

**Comment by Njuapp** [comment]
I have done cpp_lint with clang-format-9, but it still fails in CI/CD as above. I don't understand the reasons. Maybe you can help check cpp_lint too.

**Comment by narendasan** [comment]
I can fix the linting

**Review by narendasan — APPROVED** [review]
LGTM
